version: "3"
services:

  ############# External services

  memcached:
    image: memcached:1.4.38
    restart: unless-stopped

  mongodb:
    image: mongo:3.6
    # Use WiredTiger in all environments, just like at edx.org
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger
    restart: unless-stopped

  lms:
    image: ghcr.io/eol-uchile/edx-platform:testing-lilac
    volumes:
      - ../:/openedx/requirements/uchileedxlogin
    depends_on:
      - memcached
      - mongodb
