name: Python application

on:
  push:
    # branches:
    #   - 'master'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'master'

jobs:
  build:
    uses: eol-uchile/workflow-commons/.github/workflows/pythonapp.yml@356f371988e1475d231bcf8352f7875c30214602
    with:
      app_id: ${{ vars.EOLITO_BOT_APP_ID }}
      django-lms: true
      django-cms: false
      platform-eol: true
      platform-openuchile: false
    secrets:
      private_key: ${{ secrets.EOLITO_BOT_PRIVATE_KEY }}
